CREATE TABLE JUGADOR
(
  ID_jugador NUMBER(20) NOT NULL,
  Nombre VARCHAR2(50) NOT NULL,
  PRIMARY KEY (ID_jugador)
);

CREATE TABLE JUEGO
(
ID_juego NUMBER(20) NOT NULL,
Fecha_creacion TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
Estado VARCHAR2(20) NOT NULL DEFAULT 'PLANIFICADO',
PRIMARY KEY (ID_juego),
CONSTRAINT chk_Estado CHECK (Estado IN ('PLANIFICADO','EN CURSO','CONCLUIDO'))
);

CREATE TABLE JUGADA
(
  ID_jugada NUMBER(20) NOT NULL,
  ID_juego NUMBER(20) NOT NULL,
  Pasada NUMBER(1) DEFAULT 0,
  ID_jugador NUMBER(20) NOT NULL,
  PRIMARY KEY (ID_juego, ID_jugada),
  FOREIGN KEY (ID_jugador) REFERENCES JUGADOR(ID_jugador),
  FOREIGN KEY (ID_juego) REFERENCES JUEGO(ID_juego)
);

CREATE TABLE ORGANO_EN_MESA
(
  Organo VARCHAR(50)  NOT NULL,
  ID_carta NUMBER(20) NOT NULL,
  Color VARCHAR(30) NOT NULL,
  ID_jugada NUMBER(20) NOT NULL,
  ID_juego NUMBER(20) NOT NULL,
  PRIMARY KEY (ID_carta),
  CONSTRAINT chk_color_o CHECK (Color IN ('AMARILLO','ROJO','AZUL','VERDE')),
  CONSTRAINT chk_organo CHECK (Organo IN ('HUESO','CORAZON','CEREBRO','ESTOMAGO')),
  FOREIGN KEY (ID_juego,ID_jugada) REFERENCES JUGADA(ID_juego,ID_jugada),
  UNIQUE (ID_juego, ID_jugada)
);


CREATE TABLE CUBRE_ORGANO
(
  Tipo VARCHAR(20) NOT NULL,
  ID_carta NUMBER(20) NOT NULL,
  ID_jugada NUMBER(20) NOT NULL,
  ID_juego NUMBER(20) NOT NULL,
  Color VARCHAR2(30) NOT NULL,
  ID_carta_cubierta NUMBER(20) NOT NULL,
  PRIMARY KEY (ID_carta),
  CONSTRAINT chk_tipo_cubre CHECK (Tipo IN ('VIRUS', 'MEDICINA')) ,
  CONSTRAINT chk_color_c CHECK (Color IN ('AMARILLO','ROJO','AZUL','VERDE')) ,
  FOREIGN KEY (ID_carta_cubierta) REFERENCES ORGANO_EN_MESA(ID_carta),
  FOREIGN KEY (ID_juego,ID_jugada) REFERENCES JUGADA(ID_juego,ID_jugada),
  UNIQUE (ID_juego, ID_jugada)
);


CREATE TABLE JUGAR
(
  ID_jugador NUMBER(20) NOT NULL,
  ID_juego NUMBER(20) NOT NULL,
  PRIMARY KEY (ID_jugador,ID_juego ),
  FOREIGN KEY (ID_jugador) REFERENCES JUGADOR(ID_jugador),
  FOREIGN KEY (ID_juego) REFERENCES JUEGO(ID_juego)
);